## 10 Neon noir: the city as the study's sheets draw it — night-first slate
## and glass, warm windows and lamp-lit streets, magenta neon crowning the
## towers, wet paving that mirrors the lights; by day a cool, clean city
## with its neon dark. The kit in assets/ is generated by
## city/tools/styles/neon; LitPack does the rest.
extends LitPack


func _tune(e: Environment, s: DirectionalLight3D) -> void:
	NeonLook.tune(e, s)


## A cyan ring round the local player's feet.
func make_player_marker() -> Node:
	return PlayerMarker.ring(Color(str(style.get("palette", {}).get("neon_cyan", "#3FE3FF"))), 0.45)
