## 06 Cel-shaded anime: the city as the study's sheets draw it. The kit in
## assets/ is generated by city/tools/styles/anime; Pack3D assembles it,
## and this pack shades it: toon light with cool shadows, ink lines on the
## city (one full-screen pass) and on people (inverted hulls), anime faces
## that blink, a distant crowd drawn simply, and rain that wets the
## streets and opens umbrellas.
extends Pack3D

const Townscape = preload("townscape.gd")
const OUTLINE_PX := 1.4
## The parts of a person that carry an ink line: the silhouette's. The
## face, the far body and the small parts (shoes, soles, badge) do not: each
## outline is another draw of its part.
const INKED := ["skin", "top", "bottom", "hair_0", "hair_1", "hair_2", "hair_3", "hat_sun", "backpack", "jacket"]
## City Agent A1's hair, as the sheets draw it.
const A1_HAIR := Color("#2B2E6A")



func _make_town():
	return Townscape.new(style.get("palette", {}), func(path: String) -> Node3D: return _scene(path))


func _environment() -> void:
	super()
	AnimeLook.tune(env)
	AnimeLook.tune_sun(sun)


func build_world(m: Dictionary) -> bool:
	if not super(m):
		return false
	if rig != null:
		Toon.line_pass(rig.camera)
	return true


func on_shown() -> void:
	super()
	if is_inside_tree():
		AnimeLook.tune_viewport(get_viewport(), msaa_level())


func _style_node(node: Node) -> void:
	Toon.apply(node)


func set_fpv(on: bool, yaw_deg := 0.0) -> bool:
	var result := super(on, yaw_deg)
	if fpv != null:
		Toon.line_pass(fpv)
	return result


# ---- People ----

func make_occupant(view: Dictionary) -> Node:
	var root: Node3D = super(view)
	var model: Node3D = root.get_node("Model")
	var id: String = view["id"]
	var h := absi(hash(id))
	var a1 := id == str(style.get("a1", ""))
	if _is_agent(view) and not a1:
		# Agents are human-presenting guides in the uniform: their own skin,
		# hair and hair style, the shirt of their kind.
		var hair_style := h % 4
		for k in 4:
			var hair = model.find_child("hair_%d" % k, true, false)
			if hair != null:
				hair.visible = k == hair_style
		_paint(model, "hair_%d" % hair_style, _pick_colour(style.get("hair_colours", []), h / 4, "#2B2E52"))
		_paint(model, "skin", _pick_colour(style.get("skin", []), h / 16, "#F1C9A8"))
		_paint(model, "top", _colour(str(style.get("agent_shirts", {}).get(occupant_key(view), "#2F64C9"))))
		_paint(model, "bottom", _colour("#3A4466"))
		_show(model, "backpack", false)
		_show(model, "hat_sun", false)
	if a1:
		_paint(model, "top", _colour(str(style.get("agent_shirts", {}).get("CityRoleAgent", "#2F64C9"))))
		_show(model, "backpack", false)
		_show(model, "hat_sun", false)
		for k in 4:
			var hair = model.find_child("hair_%d" % k, true, false)
			if hair != null:
				hair.visible = k == 0
		_paint(model, "hair_0", A1_HAIR)
	AnimeFace.dress(model, 0 if a1 else 1 + h % 3, float(h % 997) / 997.0)
	# Toon first (runtime paints become this style's own copies), so the
	# ink passes go on those and never on a material other styles share.
	Toon.apply(model)
	_dress_far(model)
	for part in INKED:
		var n = model.find_child(part, true, false)
		if n == null:
			continue
		for mi in ([n] if n is MeshInstance3D else n.find_children("*", "MeshInstance3D", true, false)):
			Toon.outline(mi, OUTLINE_PX)
			mi.visibility_range_end = FAR_M
			mi.visibility_range_end_margin = 2.0
	# Every near part (the small ones too) gives way to the far body.
	if model.find_child("far", true, false) != null:
		_near_parts_end(model)
	return root


# ---- Rain ----

func set_rain(amount: float) -> void:
	super(amount)
	# Wet streets read darker and a touch richer.
	env.adjustment_brightness = 1.0 - 0.12 * amount
	env.adjustment_saturation = 1.12 + 0.1 * amount


func teardown() -> void:
	if is_inside_tree():
		Pack3D.restore_project_aa(get_viewport())
	super.teardown()


# ---- Player marker ----

## A vermilion ring round the local player's feet.
func make_player_marker() -> Node:
	return PlayerMarker.ring(Color(str(style.get("palette", {}).get("vermilion", "#E4513B"))), 0.45)
