"""The solarpunk kit's palette (sRGB), after the 09 Solarpunk
retro-futurism sheets: warm white ceramic and cream, blonde timber, brass,
turquoise glass, deep blue solar panels, warm sand paving, sunlit greens,
bright river blue, a cream-and-red tram, and jade and coral accents.

The pack renders these as lit, physically based materials (no toon): the
roughness and metallic tables matter. Keys shared with the anime palette
mean the same parts, so generator code can move between kits."""

PALETTE = {
    # Architecture.
    "warm_white": "#F7F3EA",
    "ceramic": "#F4F0E6",
    "ceramic_shade": "#E3DCCD",
    "cream": "#F0E4CC",
    "timber": "#D8A765",
    "timber_light": "#E8C38C",
    "timber_dark": "#A7773F",
    "brick": "#D9A765",
    "brick_light": "#E8C38C",
    "brick_dark": "#A7773F",
    "mortar": "#EFE3CE",
    "stone": "#E2D8C6",
    "stone_dark": "#BDB2A0",
    "concrete": "#E6E1D8",
    "steel": "#B9BEC4",
    "steel_light": "#DADDE1",
    "steel_dark": "#7D848C",
    "frame": "#3B3A36",
    "terracotta": "#D98C5F",
    "terracotta_dark": "#B26A43",
    "render_peach": "#F4DCC4",
    "render_sky": "#DDEAEA",
    "render_mint": "#DCEBDC",
    # Solar and glass.
    "solar": "#23489A",
    "solar_cell": "#2F5EB8",
    "solar_frame": "#D4D7DA",
    "glass": "#3E8C92",
    "glass_light": "#A6D6D2",
    "glass_tower": "#86BFC3",
    "glass_dark": "#28464A",
    "window_glow": "#FFD08A",
    "lamp_glow": "#FFE0A0",
    "fairy_glow": "#FFE9B0",
    # Ground and water.
    "paving": "#E8D7B8",
    "paving_light": "#F2E6CE",
    "paving_dark": "#D2BD98",
    "asphalt": "#8E8F8F",
    "asphalt_dark": "#747576",
    "kerb": "#E9E2D4",
    "road_line": "#F8F6F0",
    "grass": "#86B94E",
    "grass_dark": "#6CA23E",
    "soil": "#7A5A3C",
    "water": "#2B8ACB",
    "water_light": "#6CC0EC",
    "water_deep": "#1D6AA8",
    "sparkle": "#F0FAFF",
    # Plants.
    "leaf_dark": "#3D6E2C",
    "leaf": "#5A9233",
    "leaf_light": "#86BA4A",
    "leaf_sun": "#BFD66A",
    "trunk": "#6E5038",
    "trunk_light": "#8E6A4C",
    "palm": "#4F9440",
    "palm_light": "#7FBA55",
    "vine": "#4E8A34",
    "flower_white": "#FBF8F0",
    "flower_pink": "#F09AAE",
    "flower_yellow": "#FFD24F",
    "flower_coral": "#F07A5C",
    # Transit.
    "tram_cream": "#F2EDE3",
    "tram_coral": "#D6402E",
    "tram_dark": "#2F3236",
    # Wood and metal.
    "wood": "#B98352",
    "wood_light": "#D8AA74",
    "wood_dark": "#7B5534",
    "iron": "#3A3B3D",
    "brass": "#C9A152",
    "brass_dark": "#9C7A38",
    # Accents.
    "jade": "#3C9E7C",
    "jade_dark": "#2A7A5E",
    "coral": "#EE7A5C",
    "indigo": "#3E4F8F",
    "vermilion": "#E0553A",
    "blue": "#2F6FC0",
    "yellow": "#F2C14E",
    "canvas": "#F6F0E4",
    "canvas_stripe": "#3C9E7C",
    # People and agents (painted by the pack; kit defaults).
    "skin": "#E2B593",
    "cloth": "#9FB5A6",
    "hair": "#3A2A22",
    "shell": "#F4F1EA",
    "trim": "#C9A152",
    "joint": "#3A3833",
    "visor": "#101417",
    "scarf": "#3E8F5A",
    "badge": "#3E8F5A",
    "umbrella": "#3C9E7C",
    "card": "#F7F4EE",
    "book_a": "#8A3E4C",
    "book_b": "#3F5F8C",
    "book_c": "#D9B44A",
    "book_d": "#4D8A5A",
}

# Glowing colours and their emission strength (the pack scales them at night).
EMISSIVE = {"lamp_glow": 3.0, "window_glow": 1.4, "fairy_glow": 4.0}
ROUGHNESS = {
    "ceramic": 0.32, "ceramic_shade": 0.36, "warm_white": 0.5, "glass": 0.06, "glass_light": 0.08,
    "glass_tower": 0.06, "glass_dark": 0.05, "water": 0.05, "water_light": 0.08, "water_deep": 0.05, "solar": 0.18,
    "solar_cell": 0.2, "steel": 0.32, "steel_light": 0.32, "steel_dark": 0.36, "brass": 0.3,
    "brass_dark": 0.34, "shell": 0.28, "visor": 0.06, "timber": 0.62, "timber_light": 0.6,
    "timber_dark": 0.66, "leaf": 0.72, "leaf_dark": 0.74, "leaf_light": 0.7, "leaf_sun": 0.68,
    "grass": 0.85, "paving": 0.8, "paving_light": 0.78, "paving_dark": 0.82, "asphalt": 0.9,
}
METALLIC = {"steel": 0.6, "steel_light": 0.6, "steel_dark": 0.6, "brass": 0.85, "brass_dark": 0.85,
            "trim": 0.85, "solar_frame": 0.5}
