## 02 Voxel: the district in 10 cm voxels, assembled from the v2 kit in
## assets/v2/ (generated by city/tools/styles/voxel) with the voxel pilot's
## robots, desks, chairs and terminals; Pack3D does the rest from style.json.
extends Pack3D

const Townscape = preload("townscape.gd")


func _make_town():
	return Townscape.new(style.get("palette", {}), func(path: String) -> Node3D: return _scene(path), "assets/v2/")


# ---- Player marker ----

## A yellow ring, two voxel modules wide, round the local player's feet.
func make_player_marker() -> Node:
	return PlayerMarker.ring(Color(str(style.get("palette", {}).get("yellow", "#F2C230"))), 0.5)
