## 09 Solarpunk retro-futurism: the city as the study's sheets draw it —
## white ceramic and blonde timber under a warm sun, solar roofs, greenery
## everywhere, ceramic robots with brass trim and cyan eyes, fairy lights
## in the great tree by night. The kit in assets/ is generated by
## city/tools/styles/solarpunk; LitPack does the rest.
extends LitPack


func _tune(e: Environment, s: DirectionalLight3D) -> void:
	SolarpunkLook.tune(e, s)


## A jade ring round the local player's feet.
func make_player_marker() -> Node:
	return PlayerMarker.ring(Color(str(style.get("palette", {}).get("jade", "#3C9E7C"))), 0.45)
