## 11 Low-poly tropical diorama: a faceted model set with cut-away interiors.
## The district is assembled from the kit in assets/, generated by
## city/tools/styles/lowpoly; Pack3D does the rest from style.json.
extends Pack3D

const Townscape = preload("townscape.gd")


func _make_town():
	return Townscape.new(style.get("palette", {}), func(path: String) -> Node3D: return _scene(path))


# ---- Player marker ----

## A jackfruit-yellow ring round the local player's feet.
func make_player_marker() -> Node:
	return PlayerMarker.ring(Color(str(style.get("palette", {}).get("jackfruit", "#F2B632"))), 0.45)
